### ISSUE TITLE
Bug : inconsistent styles customization in modale windows 

### ISSUE THREAD

**Issue by laurentmgr** [digi-trust/cmp#148] opened 2018-07-31 15:48 UTC
Customized colors (color-background and/or color-table-background) do no apply consistently to all sections in the modale (see screenshoot)

![image](https://user-images.githubusercontent.com/41964776/43470845-d9683142-94e9-11e8-8ba2-adc14a5af07d.png)

**Comment by laurentmgr** [comment] 2018-07-31 15:50
(Note that "Information sto" is just a text selection on the screen to reveal the section)

**Comment by SupahNickie** [comment] 2018-07-31 16:08
@laurentmgr the way the CSS is done with the purposes screen, the highlighted purpose text ("information storage" in your example) is set to the background color property, which is why you can't see it with your settings the way they are. The actual settings are like so:

```
Selected Purposes:
  - text: color-background
  - background: color-primary

Other Purposes:
  - text: color-text-secondary
  - background: color-secondary
```

We can add more granular levels of CSS customization if needed however; let me know if that is needed.

**Comment by SupahNickie** [comment] 2018-08-13 17:32
Closing issue for now since it's technically working as intended. We can revisit the issue of CSS customization if prudent later.

**Closed by SupahNickie** 2018-08-13 17:32 UTC
