### ISSUE TITLE
Dynamically retrieve Purpose/Feature information in the correct language

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#23] opened 2018-04-19 14:40 UTC
Summary
The CMP should retrieve the data purpose and feature names along with their descriptions dynamically from the GVL in the correct language based on the users browser/device language

Acceptance criteria
As a CMP, when I decide to show the consent modal, I should retrieve the data purpose and feature names and descriptions from the GVLto ensure I'm showing the user up to date information in the appropriate language based on the user's language expectations
As a user, I expect to be shown data purpose and feature names and descriptions in a language I understand

**Comment by SupahNickie** [comment] 2018-05-24 19:39
Duplicate of https://github.com/digi-trust/cmp/issues/81

**Closed by SupahNickie** 2018-05-24 19:39 UTC
Labels: Beta
