### ISSUE TITLE
Translate standardised language to IAB Recommended languages

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#5] opened 2018-04-16 13:15 UTC
The IAB recommends the following languages are supported:
Bulgarian, Czech, Croatian, Danish, German, Greek, English, Spanish, Estonian, Finnish, French, Hungarian, Icelandic, Irish, Italian, Lithuanian, Latvian, Malti, Dutch, Norwegian, Polish, Portuguese, Romanian, Slovak, Slovene, Swedish and Turkish

**Comment by SupahNickie** [comment] 2018-05-24 19:39
Duplicate of https://github.com/digi-trust/cmp/issues/21

**Closed by SupahNickie** 2018-05-24 19:39 UTC
